version: '3'

services:
  frontend:
    container_name: data_breach_frontend_web
    volumes:
        - .:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: npm run serve
